"""Exercise production async cache with isolated preferences and controlled ledger fixtures."""
from pathlib import Path
import os,subprocess
root=Path(__file__).resolve().parents[1];app=root/'app/src/main/java/dev/bennett/codexmeter';out=root/'build/live-cache-verification';out.mkdir(parents=True,exist_ok=True)
fixtures={
'android/content/SharedPreferences.java':'''package android.content;public interface SharedPreferences {String getString(String k,String d);java.util.Map<String,?> getAll();Editor edit();interface Editor {Editor putString(String k,String v);void apply();}}''',
'android/content/Context.java':'''package android.content;import java.util.*;import java.util.concurrent.*;public class Context {final Map<String,SharedPreferences> stores=new ConcurrentHashMap<>();public Context getApplicationContext(){return this;}public SharedPreferences getSharedPreferences(String n,int m){return stores.computeIfAbsent(n,k->new Pref());}static class Pref implements SharedPreferences {final Map<String,String> data=new ConcurrentHashMap<>();public String getString(String k,String d){return data.getOrDefault(k,d);}public Map<String,?> getAll(){return new HashMap<>(data);}public Editor edit(){return new Editor(){public Editor putString(String k,String v){data.put(k,v);return this;}public void apply(){}};}}}''',
'dev/bennett/codexmeter/AppPreferences.java':'''package dev.bennett.codexmeter;class AppPreferences {static volatile UsageSnapshot snapshot;static UsageSnapshot loadSnapshot(android.content.Context c){return snapshot;}}''',
'dev/bennett/codexmeter/SubscriptionStore.java':'''package dev.bennett.codexmeter;class SubscriptionStore {static volatile SubscriptionCost bill;static SubscriptionCost load(android.content.Context c,UsageSnapshot s){return bill;}}''',
'dev/bennett/codexmeter/UsageApi.java':'package dev.bennett.codexmeter;class UsageApi {static final Object NETWORK_LOCK=new Object();}',
'dev/bennett/codexmeter/EvolutionWidget.java':'package dev.bennett.codexmeter;class EvolutionWidget {static volatile int calls;static void updateAll(android.content.Context c){calls++;}}',
'dev/bennett/codexmeter/DiagnosticLog.java':'package dev.bennett.codexmeter;class DiagnosticLog {static volatile int failures;static void error(android.content.Context c,String a,String b,Exception e){failures++;}}',
'dev/bennett/codexmeter/UsageLedgerDatabase.java':'''package dev.bennett.codexmeter;import java.util.*;import java.util.concurrent.*;class UsageLedgerDatabase {static volatile Data value=new Data();static volatile boolean fail;static volatile int loads;static CountDownLatch entered,release;static Data load(android.content.Context c)throws Exception {loads++;Data captured=value;if(entered!=null){CountDownLatch e=entered,r=release;entered=null;e.countDown();r.await();}if(fail)throw new IllegalStateException("isolated write/read failure");return captured;}static class Data {final List<LedgerRecord> records=new ArrayList<>();final List<Event> events=new ArrayList<>();}static class Event {String type,meter,origin;long at;Event(long t,String origin){type="credit_used";meter="";at=t;this.origin=origin;}}}''',
'dev/bennett/codexmeter/LiveCacheTest.java':'''package dev.bennett.codexmeter;import android.content.Context;import java.util.*;import java.util.concurrent.*;import java.lang.reflect.*;
public class LiveCacheTest {static int checks;static final long W=604800000L;static void check(boolean b,String m){checks++;if(!b)throw new AssertionError(m);}static UsageSnapshot snap(String plan,long at,int used){return new UsageSnapshot(plan,true,false,null,new UsageWindow(used,604800,0,(at+W/2)/1000),at);}static void waitFor(java.util.function.BooleanSupplier s)throws Exception {long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(10);while(!s.getAsBoolean()&&System.nanoTime()<end)Thread.sleep(10);check(s.getAsBoolean(),"Async worker completed");}static void pref(Context c,String n,String k,String v){c.getSharedPreferences(n,0).edit().putString(k,v).apply();}
public static void main(String[] args)throws Exception {try{Context c=new Context();long at=System.currentTimeMillis();pref(c,"secure_auth_v1","blob","fake-account-a");AppPreferences.snapshot=snap("pro",at,50);SubscriptionStore.bill=null;
check(Math.abs(LiveUsageStore.current(c).percent-12.5)<.001,"Fallback current actual counter");String stamp=LiveUsageStore.signature(c,AppPreferences.snapshot);AppPreferences.snapshot=snap("plus",at,70);check(!stamp.equals(LiveUsageStore.signature(c,AppPreferences.snapshot)),"Same timestamp different policy/counter invalidates");AppPreferences.snapshot=snap("pro",at,50);
UsageLedgerDatabase.Data data=new UsageLedgerDatabase.Data();long reset=AppPreferences.snapshot.weekly.resetAtMillis();data.records.add(new LedgerRecord("weekly","pro",at-2000,100,"100",reset,604800,"api_precise",false));data.records.add(new LedgerRecord("weekly","pro",at-1000,0,"0",reset,604800,"api_precise",false));data.records.add(new LedgerRecord("weekly","pro",at,50,"50",reset,604800,"api_precise",false));data.events.add(new UsageLedgerDatabase.Event(at-1500,"confirmed"));UsageLedgerDatabase.value=data;
int calls=EvolutionWidget.calls;final int initial=calls;LiveUsageStore.schedule(c);waitFor(()->EvolutionWidget.calls>initial);check(LiveUsageStore.current(c).bonus&&LiveUsageStore.current(c).tier==9,"Published confirmed refill tier");int loads=UsageLedgerDatabase.loads;LiveUsageStore.schedule(c);Thread.sleep(50);check(UsageLedgerDatabase.loads==loads,"Identical request coalesced");
pref(c,"secure_auth_v1","blob","fake-account-b");check(!LiveUsageStore.current(c).bonus,"Different account no old cache");pref(c,"secure_auth_v1","blob","fake-account-a");pref(c,"codex_subscription_cost","changed","new-cycle");check(!LiveUsageStore.current(c).bonus,"Billing edit invalidates cache");
pref(c,"codex_meter_settings_v1","usage_history_weekly","cleared");LiveUsageStore.invalidate();UsageLedgerDatabase.value=new UsageLedgerDatabase.Data();check(!LiveUsageStore.current(c).bonus,"Explicit clear cannot reuse consumed history");long rev=LiveUsageStore.revision();calls=EvolutionWidget.calls;final int expected=calls;LiveUsageStore.schedule(c);waitFor(()->EvolutionWidget.calls>expected);check(LiveUsageStore.revision()>rev&&!LiveUsageStore.current(c).bonus,"Empty history recalculates safely");
pref(c,"codex_meter_settings_v1","usage_history_weekly","race");UsageLedgerDatabase.value=data;UsageLedgerDatabase.entered=new CountDownLatch(1);UsageLedgerDatabase.release=new CountDownLatch(1);CountDownLatch gate=UsageLedgerDatabase.entered;LiveUsageStore.schedule(c);check(gate.await(5,TimeUnit.SECONDS),"Controlled worker enters");pref(c,"secure_auth_v1","blob","fake-account-c");UsageLedgerDatabase.value=new UsageLedgerDatabase.Data();calls=EvolutionWidget.calls;final int next=calls;LiveUsageStore.schedule(c);UsageLedgerDatabase.release.countDown();waitFor(()->EvolutionWidget.calls>next);check(!LiveUsageStore.current(c).bonus,"Old account worker result discarded");
pref(c,"codex_meter_settings_v1","usage_history_weekly","failure");UsageLedgerDatabase.fail=true;int failures=DiagnosticLog.failures;LiveUsageStore.schedule(c);waitFor(()->DiagnosticLog.failures>failures);UsageLedgerDatabase.fail=false;calls=EvolutionWidget.calls;final int retried=calls;LiveUsageStore.schedule(c);waitFor(()->EvolutionWidget.calls>retried);check(!LiveUsageStore.current(c).bonus,"Failed ledger read retry safe");
pref(c,"secure_auth_v1","blob","");AppPreferences.snapshot=null;LiveUsageStore.schedule(c);check(!LiveUsageStore.current(c).valid,"Signed out empty");
System.out.println("Production derived cache identity/billing/clear/concurrency/failure/retry: "+checks+" assertions passed (JVM fixtures).");}finally{Field f=LiveUsageStore.class.getDeclaredField("WORKER");f.setAccessible(true);((ExecutorService)f.get(null)).shutdownNow();}}
}'''
}
files=[]
for name,source in fixtures.items():
 p=out/'fixtures'/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(source,encoding='utf-8');files.append(str(p))
cp=os.pathsep.join(map(str,[out,root/'build/live-verification',root/'build/insight-verification/classes',root/'build/test-libs/json-20250517.jar']))
jdk=Path(os.environ['JAVA_HOME'])/'bin'
subprocess.run([str(jdk/'javac'),'-encoding','UTF-8','-cp',cp,'-d',str(out),str(app/'LiveUsageStore.java'),str(root/'shared/src/main/java/dev/bennett/codexmeter/SubscriptionCost.java'),*files],check=True)
subprocess.run([str(jdk/'java'),'-ea','-cp',cp,'dev.bennett.codexmeter.LiveCacheTest'],check=True,timeout=45)
